import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            <html
                lang="en"
                className="w-screen transition-all duration-500 ease-in-out"
            >
                <body className="min-h-full flex flex-col w-screen">
                    {children}
                </body>
            </html>
            <Footer />
        </>
    );
}
